# NumPy (Numerical Python)

## Introducción a NumPy

NumPy es una biblioteca fundamental del ecosistema científico de Python, diseñada para el manejo eficiente de datos numéricos y estructuras multidimensionales. Su propósito principal es proporcionar un objeto de arreglo potente y flexible, junto con un conjunto amplio de funciones matemáticas que operan de manera rápida y consistente sobre dichos datos.

### ¿Por qué se utiliza NumPy?
NumPy se utiliza porque permite realizar cálculos numéricos de forma más eficiente que las estructuras nativas de Python. Mientras que las listas estándar están pensadas para un uso general, los arreglos de NumPy están optimizados para operaciones matemáticas y científicas, lo que se traduce en un mejor rendimiento y un uso más controlado de la memoria. Además, NumPy sirve como base para muchas otras bibliotecas científicas y de análisis de datos en Python.

In [1]:
import numpy as np
print(np.__version__)

2.4.0


### El objeto central: `ndarray`

El núcleo de NumPy es el objeto `ndarray` (n-dimensional array). Este objeto representa una colección homogénea de elementos, generalmente números, organizados en una o más dimensiones. A diferencia de otras estructuras, todos los elementos de un `ndarray` comparten el mismo tipo de dato, lo que permite que las operaciones se ejecuten de forma vectorizada y eficiente.

In [7]:
arr_a = np.array([10, 5])
arr_a

array([10,  5])

In [15]:
arr_b = np.array([5, 10])
arr_b

array([ 5, 10])

In [ ]:
# la operación aplicada es una multiplicación escalar element-wise (o multiplicación por un escalar elemento a elemento).

arr_a * 2

array([20, 10])

## Data Types

NumPy ofrece una amplia variedad de tipos de datos para representar números enteros, flotantes, complejos, booleanos y más. Estos tipos de datos son cruciales para garantizar la eficiencia en el almacenamiento y procesamiento de datos. Algunos de los tipos de datos más comunes incluyen:

| Tipo de Dato |                             |
| ------------ | --------------------------- |
| integer      | (int8, int16, int32, int64) |
| float        | (int8, int16, int32, int64) |
| boolean      | (int8, int16, int32, int64) |
| string       | (int8, int16, int32, int64) |
| object       | object\_                    |


In [1]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
arr

array([1, 2, 3], dtype=int32)

In [2]:
arr.dtype

dtype('int32')

In [3]:
print(f'{arr.nbytes} bytes')

12 bytes


## Shapes

In [ ]:
import numpy as np


arr = np.array(
    [
        [[ 1,  2,  3], [ 4,  5,  6], [ 7,  8,  9]],
        [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
        [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
    ],
    dtype=np.uint16
)

In [5]:
print(arr.shape)

(3, 3, 3)


In [6]:
print(arr.ndim)

3


In [7]:
print(arr.size)

27


In [8]:
print(arr.dtype)

uint16


In [9]:
print(arr[0][0][0])  # Chain Indexing

1


In [ ]:
print(arr[0, 0, 0])  # Multi-dimensional Indexing (Faster than Chain Indexing)

1


: 