# Broadcasting

Una forma sensata de realizar operaciones elemento a elemento en arreglos de diferentes formas (pero compatibles).

$$
\begin{bmatrix}
0 & 1 & 2 \\
3 & 4 & 5
\end{bmatrix}

+

\begin{bmatrix}
0 & 1 & 2
\end{bmatrix}

=

\begin{bmatrix}
1 & 3 & 5 \\
4 & 6 & 8
\end{bmatrix}
$$

$$
\begin{bmatrix}
0 & 1 & 2 \\
3 & 4 & 5
\end{bmatrix}

+

\begin{bmatrix}
0 \\ 1 \\ 2
\end{bmatrix}

=

\begin{bmatrix}
1 & 2 & 3 \\
5 & 6 & 7
\end{bmatrix}
$$

Funciona con suma, resta, multiplicación, exponenciación, mín/máx y muchas otras operaciones elemento a elemento.

> Busca en la documentación de NumPy la palabra "Broadcasting" para ver si es compatible.

## Reglas de Compatibilidad de Shapes

1. Si x, y tienen un número diferente de dimensiones, antepón 1s al **shape** del más corto.
2. Cualquier **axis** de longitud 1 puede repetirse (**broadcast**) a la longitud del vector del otro en ese **axis**.
3. Todos los demás **axis** deben tener longitudes coincidentes.

> Usa estas reglas para calcular si los arreglos son compatibles y, de ser así, el **broadcasted shape**.

In [1]:
import numpy as np

In [2]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([[1], [2], [3]])

arr_1 + arr_2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

### Entendiendo los Axis en NumPy

Es común confundirse, pero la regla es: el **axis** indica la dimensión que se "elimina" al operar.

- **axis=0**: Operación **vertical**. Se colapsan las filas para obtener un resultado por columna.
- **axis=1**: Operación **horizontal**. Se colapsan las columnas para obtener un resultado por fila.

Visualmente:
```text
axis 1 ---->
axis 0
  |
  v
```

In [3]:
arr_z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
M = arr_z.reshape((5, 4))
M

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2],
       [3, 4, 5, 6],
       [7, 8, 9, 0]])

In [5]:
mean = M.mean(axis=0)  # Column-wise mean
mean

array([5., 4., 5., 4.])

In [26]:
mean.shape

(4,)